# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='answer_comment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='question_comment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
