# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.CharField(max_length=256, null=True)),
                ('create_time', models.DateTimeField()),
                ('img_path', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=32)),
                ('course_id', models.CharField(max_length=16, null=True)),
                ('teacher', models.ManyToManyField(related_name='teacher', to=settings.AUTH_USER_MODEL)),
                ('teaching_assitant', models.ManyToManyField(related_name='teaching_assistant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PPTfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.CharField(max_length=256, null=True)),
                ('upload_time', models.DateTimeField()),
                ('title', models.CharField(max_length=32)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PPTslice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('upload_time', models.DateTimeField(blank=True)),
                ('img_path', models.CharField(max_length=256)),
                ('pptfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.PPTfile')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('introduce', models.CharField(max_length=256, null=True)),
                ('upload_time', models.DateTimeField()),
                ('title', models.CharField(max_length=32)),
                ('video_path', models.CharField(max_length=256)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
