# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pptslice',
            name='upload_time',
            field=models.DateTimeField(),
        ),
    ]
