# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_login_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', '\u7537'), ('f', '\u5973')], default='m', max_length=1, verbose_name='\u6027\u522b'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='\u5b66\u53f7\u6216\u5de5\u53f7'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('te', '\u8001\u5e08'), ('ta', '\u52a9\u6559'), ('st', '\u5b66\u751f')], default='st', max_length=2, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='\u7528\u6237\u540d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
