# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160716_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='useravatar',
            field=models.URLField(null=True),
        ),
    ]
